# Scenario: PVC not bound
# PVC stays Pending because no StorageClass can provision it (wrong class or no provisioner).
# Pods that use this PVC will stay Pending until the PVC is Bound.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-not-bound-demo
  labels:
    scenario: pvc-not-bound
spec:
  # Use a StorageClass that does not exist → no provisioner → PVC never binds
  storageClassName: nonexistent-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-demo
  labels:
    app: pvc-demo
    scenario: pvc-not-bound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-demo
  template:
    metadata:
      labels:
        app: pvc-demo
        scenario: pvc-not-bound
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sleep", "3600"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-not-bound-demo
      resources:
        requests:
          memory: "16Mi"
          cpu: "10m"
